let fruits=["apple","orange","banana"]
console.log(fruits)
fruits.push("kiwi")
console.log(fruits)
fruits.pop()
console.log(fruits)
fruits.shift()
console.log(fruits)
fruits.unshift("papaya")
console.log(fruits)
let date=new Date()
console.log(date)
console.log(
    "year=",date.getFullYear()
)
console.log("month=",date.getMonth())
console.log("math object")
console.log("pi=",Math.PI)
console.log("maximum=",Math.max(10,20,30,40))
console.log("minimum=",Math.min(10,20,30,40))
console.log("round=",Math.round(4.7))
console.log("floor=",Math.floor(4.8))
console.log("ceil=",Math.ceil(4.2))
console.log("square root=",Math.sqrt(16))
console.log("power=",Math.pow(2,7))
